from __future__ import annotations

from typing import Mapping

_STRINGS: Mapping[str, str] = {
    "app.title": "Климозавр",
    "app.title_user": "Климозавр (Пользователь)",
    "app.close_forbidden_title": "Выход",
    "app.close_forbidden_message": "Закрытие запрещено. Выход только через меню: Меню → Выход.",
    "login.title": "Вход",
    "login.username": "Имя:",
    "login.password": "Пароль:",
    "login.button": "Войти",
    "login.close_disabled_title": "Вход",
    "login.close_disabled_message": "Закрытие отключено. Пожалуйста, выполните вход.",
    "login.invalid_title": "Вход",
    "login.invalid_message": "Неверные учетные данные.",
    "first_admin.title": "Создать администратора",
    "first_admin.username": "Логин:",
    "first_admin.password": "Пароль:",
    "first_admin.button": "Создать администратора",
    "first_admin.validation_title": "Проверка",
    "first_admin.validation_message": "Логин и пароль обязательны.",
    "first_admin.error_title": "Ошибка",
    "first_admin.error_message": "Не удалось создать пользователя: {error}",
    "device_editor.title": "Устройство",
    "device_editor.label.ip": "Хост / IP",
    "device_editor.label.name": "Имя",
    "device_editor.label.location": "Локация",
    "device_editor.label.owner": "Владелец",
    "device_editor.label.comment": "Комментарий",
    "device_editor.label.yellow_to_red_secs": "Порог до красного (сек)",
    "device_editor.label.yellow_notify_after_secs": "Уведомлять при жёлтом через (сек)",
    "device_editor.label.ping_timeout_ms": "Таймаут ping (мс)",
    "device_editor.label.icon": "Иконка PNG",
    "device_editor.label.icon_scale": "Масштаб иконки (%)",
    "device_editor.label.sound_down": "Звук недоступности (DOWN.wav)",
    "device_editor.label.sound_up": "Звук доступности (UP.wav)",
    "device_editor.button.pick": "Выбрать...",
    "device_editor.button.ok": "Готово",
    "device_editor.button.cancel": "Отмена",
    "device_editor.validation_title": "Ошибка",
    "device_editor.validation_ip_required": "Хост обязателен.",
    "device_editor.validation_ip_invalid": "Некорректный хост или IP.",
    "device_editor.file_dialog_title": "Выбор файла",
    "settings.title": "Настройки",
    "settings.label.sound_down_global": "DOWN.wav (глобальный)",
    "settings.label.sound_up_global": "UP.wav (глобальный)",
    "settings.sound_down_label": "DOWN.wav",
    "settings.sound_up_label": "UP.wav",
    "settings.button.pick": "Выбрать...",
    "settings.button.save": "Сохранить",
    "settings.button.cancel": "Отмена",
    "settings.file_dialog_title": "Выбор WAV",
    "settings.error_title": "Ошибка",
    "settings.error_missing_file": "{label}: файл не найден.",
    "user.create_title": "Создать пользователя",
    "user.set_password_title": "Сменить пароль: {username}",
    "user.field.username": "Логин *",
    "user.field.role": "Роль",
    "user.field.password": "Пароль *",
    "user.field.password_repeat": "Повтор пароля *",
    "user.field.password_new": "Новый пароль *",
    "user.field.password_repeat_short": "Повтор *",
    "user.hint_required_fields": "Поля со * обязательны.",
    "user.button.create": "Создать",
    "user.button.save": "Сохранить",
    "user.button.cancel": "Отмена",
    "user.validation_title": "Проверка",
    "user.validation_username_required": "Логин обязателен.",
    "user.validation_role_invalid": "Некорректная роль.",
    "user.validation_password_required": "Пароль обязателен.",
    "user.validation_passwords_mismatch": "Пароли не совпадают.",
    "traceroute.button.copy": "Скопировать",
    "traceroute.button.close": "Закрыть",
    "details.title": "Детали устройства",
    "details.status_label": "Статус: {status}",
    "details.rtt_label": "Задержка: {value}",
    "details.loss_label": "Потери: {value}",
    "details.last_label": "Последний ответ: {value}",
    "details.elapsed_label": "Прошло: {value}",
    "details.raw_label": "Сырые данные (последние строки)",
    "details.button.traceroute": "Трассировка (выбранное)",
    "details.button.export_selected": "Экспорт логов (выбранное)",
    "details.button.export_all": "Экспорт логов (все)",
    "details.period.1h": "1 час",
    "details.period.24h": "24 часа",
    "details.period.72h": "72 часа",
    "details.period.7d": "7 дней",
    "details.period.30d": "30 дней",
    "details.period.90d": "90 дней",
    "alerts.title": "ОПОВЕЩЕНИЯ",
    "alerts.button.ack": "Подтвердить",
    "alerts.item_text": "[{level}] устройство #{device_id}: {message}",
    "device.loss": "потери",
    "device.rtt": "задержка",
    "device.status_unstable": " • нестабильно",
    "device.meta.owner": "владелец: {value}",
    "device.meta.location": "локация: {value}",
    "device.meta.comment": "комментарий: {value}",
    "menu.title": "Меню",
    "menu.logout": "Выйти из аккаунта",
    "menu.exit": "Выход",
    "menu.export_logs_all": "Экспорт логов (все)",
    "menu.settings": "Настройки",
    "tab.monitor": "Мониторинг",
    "tab.devices": "Устройства",
    "tab.users": "Пользователи",
    "devices.button.add": "Добавить",
    "devices.button.edit": "Изменить",
    "devices.button.delete": "Удалить",
    "devices.button.import": "Импорт CSV",
    "devices.button.export": "Экспорт CSV",
    "users.button.add": "Создать пользователя",
    "users.button.delete": "Удалить",
    "users.button.password": "Сменить пароль",
    "users.button.role": "Сменить роль",
    "admin.button.refresh": "Обновить",
    "chart.series.rtt": "RTT (мс)",
    "chart.series.loss": "Потери (%)",
    "chart.axis.time": "время",
    "chart.axis.rtt": "RTT (мс)",
    "chart.axis.loss": "потери (%)",
    "dialog.export_selected_title": "Экспорт логов (выбранное)",
    "dialog.export_all_title": "Экспорт логов (все)",
    "dialog.export_completed_title": "Экспорт",
    "dialog.export_completed_message": "Логи экспортированы.",
    "dialog.settings_saved_title": "Настройки",
    "dialog.settings_saved_message": "Глобальные звуки сохранены.",
    "dialog.device_cancelled_title": "Устройства",
    "dialog.device_cancelled_message": "Отменено (диалог вернул Отмена).",
    "dialog.device_saved_title": "Готово",
    "dialog.device_saved_message": "Устройство сохранено ({action}).",
    "dialog.device_select_title": "Устройства",
    "dialog.device_select_message": "Выберите устройство в списке.",
    "dialog.user_created_title": "Готово",
    "dialog.user_created_message": "Пользователь создан.",
    "dialog.user_delete_self_title": "Пользователи",
    "dialog.user_delete_self_message": "Нельзя удалить собственный аккаунт во время входа.",
    "dialog.user_select_title": "Пользователи",
    "dialog.user_select_message": "Выберите пользователя в списке.",
    "dialog.user_password_changed_title": "Готово",
    "dialog.user_password_changed_message": "Пароль изменён.",
    "dialog.export_devices_title": "Экспорт устройств",
    "dialog.import_devices_title": "Импорт устройств",
    "dialog.export_devices_message": "Экспорт завершён.",
    "dialog.import_report_title": "Отчёт импорта",
    "dialog.import_report_summary": "добавлено={added}, обновлено={updated}, пропущено={skipped}",
    "dialog.window_open_error_title": "Ошибка",
    "dialog.window_open_error_message": "Не удалось открыть окно: {error}",
    "dialog.export_devices_filename": "devices.csv",
    "dialog.export_all_logs_filename": "all_logs.csv",
    "dialog.export_logs_filter": "CSV (*.csv)",
    "dialog.wav_filter": "WAV файлы (*.wav)",
    "dialog.png_filter": "PNG файлы (*.png)",
    "dialog.csv_filter": "CSV (*.csv)",
    "dialog.import_report_reasons_header": "Причины:",
    "traceroute.title": "Трассировка {target}",
    "admin.users_list_item": "{username} ({role})",
    "admin.devices_list_item": "{target}  |  {name}",
    "alerts.level.yellow": "Проблема",
    "alerts.level.red": "Критично",
    "alerts.level.green": "ОК",
    "alerts.level.up": "Доступен",
    "alerts.level.down": "Недоступен",
    "alerts.level.unknown": "Неизвестно",
    "alerts.message.yellow": "{level}: 100% потерь ≥ {seconds} сек",
    "alerts.message.red": "{level}: недоступно > {seconds} сек",
    "raw.status_line": "{time} статус={status} потери={loss}% задержка={rtt}",
    "raw.traceroute_start": "трассировка {target} →",
    "details.resolved_label": "IP (DNS): {value}",
    "placeholder.na": "—",
    "unit.ms": "мс",
    "unit.day_short": "д",
    "unit.hour_short": "ч",
    "unit.minute_short": "м",
    "unit.second_short": "с",
}

_STATUS_DISPLAY = {
    "GREEN": _STRINGS["alerts.level.green"],
    "YELLOW": _STRINGS["alerts.level.yellow"],
    "RED": _STRINGS["alerts.level.red"],
    "UP": _STRINGS["alerts.level.up"],
    "DOWN": _STRINGS["alerts.level.down"],
    "UNKNOWN": _STRINGS["alerts.level.unknown"],
}

_ROLE_DISPLAY = {
    "admin": "Администратор",
    "user": "Пользователь",
}


def tr(key: str, **kwargs) -> str:
    template = _STRINGS.get(key)
    if template is None:
        raise KeyError(f"Missing string key: {key}")
    return template.format(**kwargs)


def status_display(status: str) -> str:
    if not status:
        return _STATUS_DISPLAY["UNKNOWN"]
    return _STATUS_DISPLAY.get(str(status).upper(), str(status))


def role_display(role: str) -> str:
    if not role:
        return ""
    return _ROLE_DISPLAY.get(str(role).lower(), str(role))
